### ISSUE TITLE
Demo files:

### ISSUE THREAD

**Issue by zeffii** [zeffii/sods-blender-plugins#3]
darth vader wrote: 

> http://spinout182.com/mqd/object_link_boy.zobj
> http://spinout182.com/mqd/link_animetion.zdata
> http://spinout182.com/mqd/gameplay_keep.zobj
> rename link_animetion to segment_07.zdata and gameplay_keep.zobj to segment_04.zdata and keep the other filename the same
> I have no idea what the problem is and I really appreciate all of your help. thank you 
> my question:http://blender.stackexchange.com/questions/33717/typeerror-list-does-not-support-the-buffer-interface
> make sure the files are in the same folder

**Comment by zeffii** [comment]
OK, just to confirm:

no guarantee I can fix this, but blender.stackexchange isn't the place for discussing broken addons :)

note to self:

```
rename 
link_animetion.zdata     ->  segment_07.zdata
gameplay_keep.zobj       ->  segment_04.zdata
object_link_boy.zobj     ->  object_link_boy.zobj
```

is that right?

**Comment by hizeffi** [comment]
yes

**Comment by zeffii** [comment]
To test this install the addon, go to File->Import and navigate to `object_link_bpy.zobj` , then import.
