### ISSUE TITLE
importing seems to work: image:

### ISSUE THREAD

**Issue by zeffii** [zeffii/sods-blender-plugins#5]
![image](https://cloud.githubusercontent.com/assets/619340/8614689/81b7b440-26ec-11e5-9148-0efc34109825.png)

no errors in console, but I used my fixed version:
https://github.com/zeffii/sods-blender-plugins/blob/master/io_import_z64_v5.py

**Comment by zeffii** [comment]
Imports Animation too !

**Comment by hizeffi** [comment]
So it works for you, which means that the code is fine. 
![this](http://s4.postimg.org/to4b1d1m5/Untitled_1.jpg)
I still get the exact same error using your code. Is there a way to tell what is wrong? I have the latest blender, the latest python and am using your version of the plugin...

**Comment by zeffii** [comment]
The errors are mostly the same, but one of them comes from 

```
file `\Text
```

the other from

```
file "C:\Users\"
```

This leads me to believe it's an installation problem.  You are running the addon from Blender's TextEditor, don't. Also don't use TextEditor->Text->Open Text Block (to load the addon from a location on your HD) .
- remove all references to the file "io_import_z64.py" from your Harddrive, (depending on how you've installed this addon during the last days - it's likely that the addon is stored in two or more separate places - doing a system wide search for that file will tell you if that's the case - delete them all)

By far the simplest way to install an addon is to stick it inside the folder `"addons"` inside `scripts`, see [this for more information](https://www.blender.org/manual/getting_started/installing_blender/directorylayout.html) where these folders are found on various operating systems, then enable in the addons tab in User Preferences.

![image](https://cloud.githubusercontent.com/assets/619340/8632546/2664bbf6-27a0-11e5-9b5d-90a79819c2ba.png)

EIther stick it inside "addons" or "addons_contrib". If you don't have an addons_contrib folder inside scripts, then you can simply create it. The reason I like to use "addons_contrib" is to destinguish addons that are official, from community created ones, the official convention is to use "addon_contrib".

**Comment by zeffii** [comment]
https://raw.githubusercontent.com/zeffii/sods-blender-plugins/master/io_import_z64_v5.py

**Comment by hizeffi** [comment]
http://s4.postimg.org/vh77pomst/screenshot_31.png
I installed it in that folder and it still gives me this error

**Comment by hizeffi** [comment]
(It's your version, I just didn't rename the file to v5)

**Comment by zeffii** [comment]
rename to v5 so there is no confusion, it won't affect the operation of the code.

OK, i don't know if this can be solved easily. Blender is bundled with it's own Python 3.4.x (built straight into the blender executable) - and that's what it should be using.

But there are ways to tell Blender (using system Path variables ) to use an alternative (older version) of Python. -- which is something you shouldn't be doing, but can happen without you explicitly setting that path. 

When you go to Blender's python console and do this: (and hit enter)

``` python
>>> bpy.app.binary_path_python
```

what is the output?

**Comment by zeffii** [comment]
Also:  in the Text Editor, paste this and see what it returns

```
import sys
print(sys.version)
```

**Comment by hizeffi** [comment]
'C:\Program Files\Blender Foundation\Blender\2.75\python\bin\python.EXE'
![this_way](http://s4.postimg.org/eupngltv1/screenshot_32.png)

**Comment by zeffii** [comment]
OK, good. I feel more confident that the code is being executed by python 3.4.2 now :)

This could be a bug specific to the windows implementation of Python, or the addon wasn't fully stress tested to work on Windows.  There are several points in the addon that worry me - in the sense that the code may not be entirely cross platform.

**Comment by hizeffi** [comment]
So there's no way to fix it?

**Comment by zeffii** [comment]
https://github.com/zeffii/sods-blender-plugins/blob/master/io_import_z64_v5.py#L91
https://github.com/zeffii/sods-blender-plugins/blob/master/io_import_z64_v5.py#L100
https://github.com/zeffii/sods-blender-plugins/blob/master/io_import_z64_v5.py#L113
https://github.com/zeffii/sods-blender-plugins/blob/master/io_import_z64_v5.py#L1392

the platform independant way to make paths is 

``` python
import os
filepath = os.path.join("a", "b")
```

not (as is currently the case)

``` python
filepath = "a" + "/b"
```

I will have opportunity to test this on a windows machine tomorrow, or later today.

**Comment by hizeffi** [comment]
so you're changing  os.mkdir(fpath + "/textures")
to  os.path.mkdir(fpath + "/textures") ?

**Comment by zeffii** [comment]
i'll make a `io_import_z64_v5b.py`, for you to test.. it's only a few lines - hang on

**Comment by zeffii** [comment]
https://raw.githubusercontent.com/zeffii/sods-blender-plugins/master/io_import_z64_v5b.py

**Comment by zeffii** [comment]
I can't test this on windows, but "paths" are often a problem for people who aren't used to coding for multiple platforms. The changes are really minimal, but without them I wouldn't be suprised the addon fails on your Windows machine but works on my Linux box.

the changes:
https://github.com/zeffii/sods-blender-plugins/blob/master/io_import_z64_v5b.py#L91
https://github.com/zeffii/sods-blender-plugins/blob/master/io_import_z64_v5b.py#L101-L102
https://github.com/zeffii/sods-blender-plugins/blob/master/io_import_z64_v5b.py#L117-L118
https://github.com/zeffii/sods-blender-plugins/blob/master/io_import_z64_v5b.py#L1398-L1399

**Comment by hizeffi** [comment]
http://s4.postimg.org/y17fxizql/screenshot_33.png
http://s4.postimg.org/y2hdqy1kd/screenshot_34.png
it gives a different error now...
thank you for everything you've done already :)

**Comment by zeffii** [comment]
OK, that's a small mistake on my part. one moment

**Comment by zeffii** [comment]
https://github.com/zeffii/sods-blender-plugins/commit/2c4097359bf61e62b3e63dcf14ddd4b22394a5a6  - download it again

**Comment by hizeffi** [comment]
http://s4.postimg.org/d6v3fp5d9/screenshot_35.png
http://s4.postimg.org/r1tdy5zsd/screenshot_36.png
now it's back to the old error message :/

**Comment by zeffii** [comment]
do me a favour and don't rename the file.

**Comment by hizeffi** [comment]
I'm actually changing the file's contents

**Comment by zeffii** [comment]
OK. delete the file from that directory, and download the `io_import_z64_v5b.py` into it instead. The file you are reusing might have hidden characters.

**Comment by hizeffi** [comment]
I did that and I think the reason it didn't work is because I clicked on external anim and majorasanim
but now, even though it supposedly imported the animations, I get this:
http://s4.postimg.org/d9ez2j90t/screenshot_37.png

**Comment by hizeffi** [comment]
Do you know why the animation doesn't play?

**Comment by zeffii** [comment]
starting point
![image](https://cloud.githubusercontent.com/assets/619340/8633031/95e749ba-27b6-11e5-8318-2fdec939d13a.png)

selecting `object_link_boy.zobj`, and import using zelda64 importer
![image](https://cloud.githubusercontent.com/assets/619340/8633038/e02e1760-27b6-11e5-83a2-1a19a6f8f586.png)

you see the addon generates a textures folder. Delete this folder and try again.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/8633047/42d9e9b6-27b7-11e5-80cc-c01d08897e6d.png)
that image looks like it is in 'rest position' , try ' pose position'

**Comment by zeffii** [comment]
does this work now or what?

**Comment by hizeffi** [comment]
Never mind, I restarted blender and it worked perfectly. Thank you so much

**Comment by zeffii** [comment]
cool. well, at least addon has gotten an extention in life, I will delete the test redundant py files now.
